// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // To add seed CLI in prisma 
      // seed: "node prisma/seeds.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
